gestion_blog_homepage:
    path:     /
    defaults: { _controller: Gestion_BlogBundle:Default:index }

ajouter:
    path:     /ajouter-article
    defaults: { _controller: Gestion_BlogBundle:Gestion_Articles:ajouter }

afficher_liste:
    path:     /articles
    defaults: { _controller: Gestion_BlogBundle:Gestion_Articles:Affiche_list_article }
