Blog_Homepage_User:
    path:     /
    defaults: { _controller: Gestion_BlogBundle:Default:index }

ajouter_article_Admin:
    path:     /admin/ajouter-article
    defaults: { _controller: Gestion_BlogBundle:Gestion_Articles:ajouter }

gestion_blog_homepage_Admin:
    path:     /admin/gestion-blog
    defaults: { _controller: Gestion_BlogBundle:Gestion_Articles:Affiche_list_article }
